version: '2.4'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: contracts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - ../go-contracts-crud-db/:/var/lib/postgresql/data/

  app:
    build:
      context: .
      dockerfile: build/app.Dockerfile
    image: contracts
    entrypoint: /docker-app
    depends_on:
      - db
    environment:
      DATABASE_URI: postgres://postgres:password@db/contracts
      RUN_ADDRESS: 0.0.0.0:8080
    ports:
      - "127.0.0.1:8080:8080"
